package horse_reserved.model;

public enum AuditAccion {
    // AUTENTICACION
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    REGISTRO_EXITOSO,
    LOGOUT,
    OAUTH2_LOGIN_EXITOSO,
    OAUTH2_LOGIN_FALLIDO,

    // RESERVA
    RESERVA_CREADA,
    RESERVA_ACTUALIZADA,
    RESERVA_CANCELADA,

    // RECURSO_ADMIN
    RUTA_CREADA,
    RUTA_ACTUALIZADA,
    CABALLO_CREADO,
    CABALLO_ACTUALIZADO,
    CABALLO_ESTADO_CAMBIADO,
    GUIA_CREADO,
    GUIA_ACTUALIZADO,
    GUIA_ESTADO_CAMBIADO,

    // CUENTA
    CAMBIO_PASSWORD,
    RESET_PASSWORD_SOLICITADO,
    RESET_PASSWORD_COMPLETADO,

    // SISTEMA
    ERROR_INTERNO
}
